// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID              string `json:"id"`
	Title           string `json:"title"`
	AuthorFirstName string `json:"authorFirstName"`
	AuthorLastName  string `json:"authorLastName"`
	Genre           string `json:"genre"`
}

type NewBook struct {
	Title           string `json:"title"`
	AuthorFirstName string `json:"authorFirstName"`
	AuthorLastName  string `json:"authorLastName"`
	Genre           string `json:"genre"`
}
